### ISSUE TITLE
Error  ./manage.py migrate

### ISSUE THREAD

**Issue by jhonvidal** [mishbahr/djangocms-twitter2#1]
help me, please: 

```
Operations to perform:
  Apply all migrations: djangocms_inherit, portfolio, cmsplugin_contact_plus, easy_thumbnails, djangocms_file, sites, blog, menus, contenttypes, connected_accounts, djangocms_googlemap, filer, sessions, reversion, djangocms_column, auth, djangocms_twitter, djangocms_picture, djangocms_style, admin, djangocms_link, djangocms_video, taggit, djangocms_teaser, cms, djangocms_text_ckeditor
Running migrations:
  Rendering model states... DONE
  Applying djangocms_twitter.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jhon/MEGAsync/binanova/proyectos/binaweb/ciga/implementacion/vciga/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/jhon/MEGAsync/binanova/proyectos/binaweb/ciga/implementacion/vciga/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jhon/MEGAsync/binanova/proyectos/binaweb/ciga/implementacion/vciga/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jhon/MEGAsync/binanova/proyectos/binaweb/ciga/implementacion/vciga/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/jhon/MEGAsync/binanova/proyectos/binaweb/ciga/implementacion/vciga/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/jhon/MEGAsync/binanova/proyectos/binaweb/ciga/implementacion/vciga/lib/python2.7/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/jhon/MEGAsync/binanova/proyectos/binaweb/ciga/implementacion/vciga/lib/python2.7/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/jhon/MEGAsync/binanova/proyectos/binaweb/ciga/implementacion/vciga/lib/python2.7/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/jhon/MEGAsync/binanova/proyectos/binaweb/ciga/implementacion/vciga/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.state_forwards(self.app_label, project_state)
  File "/home/jhon/MEGAsync/binanova/proyectos/binaweb/ciga/implementacion/vciga/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 53, in state_forwards
    list(self.managers),
  File "/home/jhon/MEGAsync/binanova/proyectos/binaweb/ciga/implementacion/vciga/lib/python2.7/site-packages/django/db/migrations/state.py", line 367, in __init__
    'Use a string reference instead.' % name
ValueError: ModelState.fields cannot refer to a model class - "account.to" does. Use a string reference instead.
```

**Comment by mishbahr** [comment]
I was unable to reproduce the issue using: 

```
* django (1.8.13)
* django-cms (3.3.0)
* djangocms-twitter2 (0.1.1)
* django-connected (0.1.4)
```

**Comment by mishbahr** [comment]
I think I found the issue, its related to `https://github.com/mishbahr/django-connected`.

I fixed this issue long time ago (https://github.com/mishbahr/django-connected/commit/1ee81bfd0efc708f16dd4b957f80705c36122c20), but somehow forgot to publish it on PyPi! Sorry.

I'll do it tonight, as soon as I get home. Many thanks for reporting this issue.

Regards

Mishbah

**Comment by mishbahr** [comment]
Fixed. I uploaded the latest changes to https://github.com/mishbahr/django-connected to PyPi.

https://pypi.python.org/pypi/django-connected
